### ISSUE TITLE
Cannot resize window

### ISSUE THREAD

**Issue by funkatron** [spazproject/spaz-desktop-titanium#1]
Nothing to drag!

**Comment by joshthecoder** [comment]
Yeah that only seems to work if the chrome is enabled.

**Comment by funkatron** [comment]
It was working before I put in the new themes. it's flakey, but it does work (see https://gist.github.com/802288). Making it more performant may be something to be solved in Titanium Desktop, tho.

**Comment by funkatron** [comment]
basically fixed until TiD is updated
