### ISSUE TITLE
All notifications "stack" on top of each other

### ISSUE THREAD

**Issue by ivkowalenko** [spazproject/spaz-desktop-titanium#11]
When multiple notifications pop up, they all pop up on top of each other, obscuring each other.
Example: http://i.imgur.com/bm1lV.png

Tested on Mac OS X 10.6.7

**Comment by funkatron** [comment]
do you have growl installed? doesn't do that for me on OS X

**Comment by ivkowalenko** [comment]
Growl is installed, but it is disabled. Also I'm pretty sure I'm not using that display style for Growl (though I could be wrong, I haven't looked at it in a while). After re-enabling and re-disabling Growl (as well as changing the display style) I can confirm that this is not related to Growl. Furthermore, as the displays come up and disappear Spaz (specifically indicated as Spaz at least) will steal keyboard focus.

**Comment by funkatron** [comment]
I have growl installed, and this works correctly. I think you are seeing an issue with notifications that are generated by titanium itself. You may want to change your notification type to "Internal"
