### ISSUE TITLE
Styles aren't being applied for Windows build

### ISSUE THREAD

**Issue by szul** [spazproject/spaz-desktop-titanium#5]
The styles aren't being applied on the Windows build. An image has been sent to the @spaz identi.ca account. This for Windows 7. I haven't tried the Mac version. I experienced this once before with the AIR version, but restarting the app fixed it. Subsequent restarts with the Titanium version didn't, however. I'll try running this on Windows from source later in the week.

**Comment by funkatron** [comment]
Might be a path issue of some sort. will need to actually test on Windows.

**Comment by szul** [comment]
Yeah. I'm downloading the tools needed for Git on Windows now. I'll fork it and do some testing and debugging - probably this weekend.

**Comment by szul** [comment]
The latest Windows build resolved this issue.
