### ISSUE TITLE
App loads sans CSS and apparently javascript.

### ISSUE THREAD

**Issue by spooons** [spazproject/spaz-desktop-titanium#6]
I installed on Windows 7 Ultimate 32bit using the MSI installer. I ran spaz.exe and received a transparent, unstyled, spaz window. Some of the buttons respond to my clicks (minimize, close, etc), but obviously something is wrong. 

I uninstalled Spaz-Air so I could install this in the default spaz directory (just in case that was the issue), and still get the broken window.

When i close I do hear the Spaztastic bells ringing.

http://twitpic.com/4c4whu

**Comment by szul** [comment]
This is a duplicate of issue #5.

**Comment by spooons** [comment]
yea i was so busy complaining publicly like a retard (aka: spaz) that I came in a minute too late with the appropriate bug report. MY FAULT.

**Comment by szul** [comment]
I'm just glad to see that it wasn't something that I did wrong with the install :)

**Comment by spooons** [comment]
me too!
