### ISSUE TITLE
OS X window resizing broken

### ISSUE THREAD

**Issue by carl67lp** [spazproject/spaz-desktop-titanium#7]
Mac OS X version

I narrowed the window from its default to a smaller size, and in doing so, all the text got cut off, and I lost the resizing widget in the corner.

Quitting and restarting does not fix the problem.

This is with the build released on the morning of March 22, 2011.

**Comment by funkatron** [comment]
You'll need to delete your prefs file to fix. This is otherwise related to issues in #8 (I just made it), so closing this.
