### ISSUE TITLE
Resizing is flakey

### ISSUE THREAD

**Issue by funkatron** [spazproject/spaz-desktop-titanium#8]
Slow, prone to freakouts, doesn't respect min win size. Will likely be fixed by Titanium Desktop changes.

**Comment by ivkowalenko** [comment]
I've also noticed that I cannot resize the window in such a way that its shadow goes beyond the edge of the screen. I can _move_ it beyond the edge of the screen, I just can't resize it.

**Comment by funkatron** [comment]
I've changed the Leopaz and Spaz Mini themes to work with native chrome, which works much better.
