### ISSUE TITLE
Apps Crashes When Loading on Win7

### ISSUE THREAD

**Issue by szul** [spazproject/spaz-desktop-titanium#9]
The app installed and loaded successfully; however, after adding an account, the application crashed. Start attempts thereafter also crashed.

This is on Windows 7 32-bit. The account was an identi.ca account.

Not sure if/where Titanium outputs a crash log. I got Git sorted out on my Windows box yesterday, so I'm hoping to run a forked version of the source tomorrow or Friday when I get a chance.

**Comment by funkatron** [comment]
Yep. I see the same here. If you can try to track it down that would be cool. Titanium seems… crash prone.

## 

Ed Finkler
http://funkatron.com
@funkatron
AIM: funka7ron / ICQ: 3922133 / XMPP:funkatron@gmail.com

**Comment by funkatron** [comment]
This seems to be a known issue with Titanium Desktop 1.1. Don't know about a timetable for a fix.
